image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_GITLAB: registry.gitlab.com/deadblackclover/hacktheplanet
  CONTAINER_TAG: latest
  CONTAINER_HEROKU: registry.heroku.com/hacktheplanet-rust/web

stages:
  - dockerize
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

dockerize:
  stage: dockerize
  script:
    - docker build -t $CONTAINER_GITLAB:$CONTAINER_TAG .
    - docker push $CONTAINER_GITLAB:$CONTAINER_TAG
  only:
    - master

deploy_to_heroku:
  stage: deploy
  environment:
    name: staging
    url: https://hacktheplanet-rust.herokuapp.com/
  services:
    - docker:dind
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CONTAINER_GITLAB:$CONTAINER_TAG
    - docker tag $CONTAINER_GITLAB:$CONTAINER_TAG $CONTAINER_HEROKU
    - docker push $CONTAINER_HEROKU
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release worker --app hacktheplanet-rust
  only:
    - master
